### ISSUE TITLE
SendMessageAsync error 

### ISSUE THREAD

**Issue by Joeljyothish** [Terraria-Builders-Community/Terraqord#1]
![Screenshot_20230223-200143](https://user-images.githubusercontent.com/124558369/220941546-cbb3767e-7e5a-491b-8825-19162d6583de.png)

**Comment by xtpkt** [comment]
https://github.com/Joeljyothish/TerraQord

You ripped the plugin and butchered it into your own independent repository, not even a proper fork -- and now you want to submit an issue regarding "your" plugin?

Get lost.

**Comment by RenderBr** [comment]
GO AWAY GOLDENWOLF

**Comment by Evauation** [comment]
lmao

**Comment by Joeljyothish** [comment]
> GO AWAY GOLDENWOLF

???

**Comment by Joeljyothish** [comment]
> https://github.com/Joeljyothish/TerraQord
> 
> You ripped the plugin and butchered it into your own independent repository, not even a proper fork -- and now you want to submit an issue regarding "your" plugin?
> 
> Get lost.

I forgot that how do I fix this
